### PR TITLE
use reducedSize to keep layout as it was before the breaking changes …

### PR DESCRIPTION
**Pull request by JorgeMartinezPizarro**
…in GUI elements

### CODE REVIEW

**Comment by chriswartner** [comment]
Bildschirmfoto vom 2019-07-01 11-16-45

Please align text and checkboxes and remove blank space at the bottom.

**Comment by JorgeMartinezPizarro** [comment]
@chriswartner I fixed the observed bugs.

**Comment by JorgeMartinezPizarro** [comment]
Thank you for your time.

**Comment by JorgeMartinezPizarro** [comment]
Hi @andreas-schultz 

it seems that the select boxes are broken with my update. Did you checked it on your laptop? Could you please take a look and validate it?

**Comment by andreas-schultz** [comment]
https://github.com/silk-framework/silk/pull/285 fixes the same issue.

**Pull request closed without merging**
